etcd:
  command: >
    --advertise-client-urls http://127.0.0.1:2379
    --data-dir /var/lib/etcd
    --listen-client-urls http://127.0.0.1:2379
    --listen-peer-urls http://127.0.0.1:2380
    --name etcd0
  image: "quay.io/coreos/etcd:v2.0.12"
  net: "host"
  restart: "always"
  volumes:
    - /var/lib/etcd:/var/lib/etcd
    - ~/.boot2docker/certs/boot2docker-vm/:/etc/ssl/certs

apiserver:
  command: >
    --allow_privileged=true
    --insecure-bind-address=0.0.0.0
    --insecure-port=8080
    --kubelet_https=true
    --service-cluster-ip-range=10.100.0.0/16
    --etcd-servers=http://172.17.8.100:2379
    --logtostderr=true
  image: "mattma/kube-apiserver:1.0.1"
  net: "host"
  restart: "always"
  volumes:
    - /etc/kubernetes:/etc/kubernetes
    - ~/.boot2docker/certs/boot2docker-vm/:/etc/ssl/certs
    - /var/run/kubernetes:/var/run/kubernetes

controllermanager:
  command: >
    --master=http://127.0.0.1:8080
    --logtostderr=true
  image: "mattma/kube-controller-manager:1.0.1"
  net: "host"
  restart: "always"
  volumes:
    - /etc/kubernetes:/etc/kubernetes
    - ~/.boot2docker/certs/boot2docker-vm/:/etc/ssl/certs

scheduler:
  command: >
    --master=http://127.0.0.1:8080
    --logtostderr=true
  image: "mattma/kube-scheduler:1.0.1"
  net: "host"
  restart: "always"
  volumes:
    - /etc/kubernetes:/etc/kubernetes
    - ~/.boot2docker/certs/boot2docker-vm/:/etc/ssl/certs

kubelet:
  command: >
    --address=0.0.0.0
    --port=10250
    --hostname_override=${ETH1_IPV4}
    --api_servers=http://172.17.8.100:8080
    --allow_privileged=true
    --logtostderr=true
    --healthz_bind_address=0.0.0.0
    --healthz_port=10248
  image: "mattma/kubelet:1.0.1"
  net: "host"
  privileged: true
  restart: "always"
  volumes:
    - /usr/bin/nsenter:/nsenter
    - /usr:/usr
    - /lib64:/lib64
    - /:/rootfs:ro
    - /etc/kubernetes:/etc/kubernetes
    - /etc/os-release:/etc/os-release
    - ~/.boot2docker/certs/boot2docker-vm/:/etc/ssl/certs
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw

proxy:
  command: >
    --master=http://172.17.8.100:8080
    --logtostderr=true
  image: "mattma/kube-proxy:1.0.1"
  net: "host"
  privileged: true
  restart: "always"
  volumes:
    - /etc/kubernetes:/etc/kubernetes
    - ~/.boot2docker/certs/boot2docker-vm/:/etc/ssl/certs
    - /usr:/usr
    - /lib64:/lib64
