#!/bin/sh

if [ ! -f settings ]; then
  echo "Error loading configuration; settings file missing."
  exit 1
fi

source settings

for b in kube-apiserver kube-proxy kube-scheduler kube-controller-manager kubelet; do
  docker tag -f ${b}:${KUBERNETES_VERSION} ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USERNAME}/${b}:${KUBERNETES_VERSION}
  docker push ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USERNAME}/${b}:${KUBERNETES_VERSION}
done
